version: "3.3"

services:
  postgres:
    image: postgres:12.0
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  swagger:
    image: swaggerapi/swagger-ui
    restart: on-failure
    environment:
      SWAGGER_JSON: /docs/swagger.yml
    volumes:
      - ./docs:/docs
    ports:
      - "8080:8080"

volumes:
  postgres-data: {}
