log:
  level: "debug"
  mode:  "dev"

server:
  shutdown_timeout: "15s"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "10s"

database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
  database: operations
  ssl_mode: disable

worker:
  insert_batch_size: 1000
  package_id: "06779371-308f-42d7-895e-5a39833375f0"

nats:
  host: "127.0.0.1"
  port: 4222
  user: "opencars"
  password: "opencars"
