log:
  level: "debug"
  mode:  "dev"

server:
  shutdown_timeout: "15s"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "10s"

database:
  host: 164.90.242.241
  port: 5432
  username: postgres
  password: NvBD8kieBorVaWUh
  database: operations
  ssl_mode: require

worker:
  insert_batch_size: 10000
  package_id: "06779371-308f-42d7-895e-5a39833375f0"
